BREAKING CHANGE!: sync aerial & navic highlights with treesitter & lsp highlights
gbprod/nord.nvim pull request #30
Opened 2023-03-18 06:11 UTC by Isrothy

Link Aerial and Navic highlights to treesitter and lsp highlights.
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/61075605/226088417-bc748a7d-3801-4918-98dc-0e5b7641df19.png">

2023-03-20 07:58 UTC, gbprod commented
Hey!
Thanks for your PR!
Does it breaks compat with neovim 0.8 ? I think I should pass #26 before.

2023-03-23 14:02 UTC, Isrothy commented
Default semantic token values have been added

2023-03-27 07:18 UTC, gbprod requested changes

2023-03-27 07:18 UTC, gbprod commented on lua/nord/treesitter.lua
> +    ["@lsp.type.enumMenber"] = { link = "@constant" },
Typo : `enumMember`

2023-03-27 07:59 UTC, Isrothy commented
fixed

2023-03-27 09:50 UTC, gbprod approved these changes

2023-03-27 09:51 UTC, merged

2023-03-27 09:51 UTC, gbprod commented
thanks