Support bufferline
gbprod/nord.nvim pull request #4
Opened 2022-12-03 07:56 UTC by Isrothy

Support [bufferline](https://github.com/akinsho/bufferline.nvim)

2022-12-03 09:26 UTC, Isrothy commented
Also support notify

2022-12-03 09:58 UTC, Isrothy commented
support [nvim-ts-rainbow](https://github.com/p00f/nvim-ts-rainbow)

<img width="251" alt="image" src="https://user-images.githubusercontent.com/61075605/205435122-e534af26-c3f0-41d6-b50e-4b98d800f5b7.png">

2022-12-04 17:24 UTC, Isrothy commented
NeoTree support
<img width="362" alt="image" src="https://user-images.githubusercontent.com/61075605/205505727-0660c24b-4805-458e-be20-81a8aef183ef.png">

2022-12-04 20:31 UTC, gbprod requested changes
Just a quick review for the moment, I'm not sure about your bufferline integration. I'll review this more tomorrow

2022-12-04 20:31 UTC, gbprod commented on .gitignore
> +.luarc.json
Can you remove this please 😉

2022-12-04 20:31 UTC, gbprod commented on lua/nord/colors.lua
> +  nord14 = "#A3BE8C",
Please use already defined color and do not duplicate.

2022-12-05 04:24 UTC, Isrothy commented
Done

2022-12-05 08:11 UTC, gbprod commented
Thanks for your work!

Please, next time, create 1 PR by plugin. 
I have a lot of little changes to do, I think it will be easier if I do it by myself. 
I'm working on a way to customize this theme more clearly, so, the bufferline api will change.

I think I'll merge this PR in a separate branch and apply my changes, I'll notify you for reviews.

2022-12-05 08:13 UTC, merged

2022-12-05 08:44 UTC, Isrothy commented
Thanks a lot for reviewing!

May I ask what do you mean by "create 1 PR by plugin"? Does it mean plugins like [octokit-plugin-create-pull-request](https://github.com/gr2m/octokit-plugin-create-pull-request)? (just googled it)
Thanks for your time.